parameters:
    app.name: 'GOSA'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Gosa\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Gosa\UI\Backoffice\Controller\:
        resource: '../src/UI/Backoffice/Controller/'
        tags: ['controller.service_arguments']
        public: true
